pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
  }
  
  stages {
  	stage('Generating Swagger API') {
  		steps {
  			dir(path: 'eclipse-based-ide/developmentTools/modules/openApiClientBuilding') {
  				sh 'java -jar swagger-codegen-cli-3.0.7.jar generate -i openapi.json -l java -o client -c codegen-java-config.json'
  			}
  		}
  	}
  	stage('Building Swagger API') {
  		steps {
  			dir(path: 'eclipse-based-ide/developmentTools/modules/openApiClientBuilding/client') {
  				sh 'mvn clean install -DskipTests'
  			}
  		}
  	}
  	stage('Testing Swagger API') {
  		steps {
  			dir(path: 'eclipse-based-ide/developmentTools/modules/openApiClientBuilding/client') {
  				sh 'mvn test integration-test'
  			}
  		}
  	}
    stage('Build CROSSMINER IDE') {
      steps {
        dir(path: 'eclipse-based-ide/org.eclipse.scava.root') {
          sh 'mvn clean install -DskipTests'
        }
      }
    }
    stage('Test CROSSMINER IDE') {
      steps {
        dir(path: 'eclipse-based-ide/org.eclipse.scava.root') {
          sh 'mvn test integration-test'
        }
      }
      post {
        success {
        	archiveArtifacts 'eclipse-based-ide/org.eclipse.scava.root/releng/org.eclipse.scava.update/target/repository/**'
        }
      }
    }
  }
  post {
    always {
	  	junit '**/target/surefire-reports/TEST-*.xml'
		}
  }
}

