pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
  }
  
  stages {
  	stage('Generating Swagger API') {
  		steps {
  			dir(path: 'eclipse-based-ide/developmentTools2/openApi') {
  				sh 'java -jar swagger-codegen-cli-3.0.7.jar generate -i openapi.json -l java -o ./projects/client -c codegen-java-config.json'
          sh 'rm -rf ./projects/client/src/test/'
  			}
  		}
  	}
  	stage('Building Swagger API') {
  		steps {
  			dir(path: 'eclipse-based-ide/developmentTools2/openApi/projects/client') {
  				sh 'mvn clean install -DskipTests'
  			}
  		}
  	}
  	stage('Testing Swagger API') {
  		steps {
  			dir(path: 'eclipse-based-ide/developmentTools2/openApi/projects/client') {
  				sh 'mvn test integration-test'
  			}
  		}
  	}
    stage('Build CROSSMINER IDE') {
      steps {
        dir(path: 'eclipse-based-ide/org.eclipse.scava.root') {
          sh 'rm ./bundles/org.eclipse.scava.plugin/lib/org.eclipse.scava.java.m3*'
          sh 'wget -P ./bundles/org.eclipse.scava.plugin/lib/ -N "https://github.com/crossminer/java-m3/releases/download/0.0.1-SNAPSHOT/org.eclipse.scava.java.m3-0.0.1-SNAPSHOT-jar-with-dependencies.jar"'
          sh 'mvn clean install -DskipTests'
        }
      }
    }
    stage('Test CROSSMINER IDE') {
      steps {
        dir(path: 'eclipse-based-ide/org.eclipse.scava.root') {
          sh 'mvn test integration-test'
        }
      }
      post {
        success {
        	archiveArtifacts 'eclipse-based-ide/org.eclipse.scava.root/releng/org.eclipse.scava.update/target/repository/**'
        }
      }
    }
  }
  post {
    always {
	  	junit allowEmptyResults: true, testResults: '**/target/surefire-reports/TEST-*.xml'
		}
  }
}

