/*
 * generated by Xtext 2.16.0
 */
package org.eclipse.scava.crossflow.language.xtext.ide


/**
 * Use this class to register ide components.
 */
class CrossflowIdeModule extends AbstractCrossflowIdeModule {
}
