package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

public interface MdeTechnologyClonedRepoEntriesForAuthorCounterConsumer {
	
	void consumeMdeTechnologyClonedRepoEntriesForAuthorCounterWithNotifications(ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple);
	
}