package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

public interface MdeTechnologyClonedRepoEntriesForOwnerPopularityCounterConsumer {
	
	void consumeMdeTechnologyClonedRepoEntriesForOwnerPopularityCounterWithNotifications(ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple);
	
}