package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

public interface MdeTechnologyRepoFileCountEntriesConsumer {
	public void consumeMdeTechnologyRepoFileCountEntries(StringStringIntegerStringIntegerTuple stringStringIntegerStringIntegerTuple);
}