package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

public interface MdeTechnologyRepoOwnerPopularityCountEntriesConsumer {
	public void consumeMdeTechnologyRepoOwnerPopularityCountEntries(StringStringIntegerStringIntegerTuple stringStringIntegerStringIntegerTuple);
}