pipeline {
  agent any
  options {
    disableConcurrentBuilds()  //each branch has 1 job running at a time
    buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '1'))
  }
  stages {
    stage('Build Knowledge Base') {
      steps {
        configFileProvider([configFile(fileId: 'fe9a3595-f02f-47eb-b1cd-9863a4e8915b', variable: 'MY_KB_APP_PROP')]) {
          dir(path: 'knowledge-base/org.eclipse.scava.knowledgebase/') {
            sh "cp $MY_KB_APP_PROP src/test/resources/application.properties"
            sh 'mvn validate'
            sh 'mvn clean compile'
            sh 'mvn package -Dmaven.test.skip=true'
          }
        }
      }
    }
    stage('Test Knowledge Base') {
      steps {
        lock('knowledge-base-test-lock') {
            configFileProvider([configFile(fileId: 'fe9a3595-f02f-47eb-b1cd-9863a4e8915b', variable: 'MY_KB_APP_PROP')]) {
                dir(path: 'knowledge-base/org.eclipse.scava.knowledgebase/') {
                	sh 'rm -rf /tmp/scava_lucene/'
                    sh "cp $MY_KB_APP_PROP src/test/resources/application.properties"
                    sh 'mvn test'
                }
            }
            junit(testResults: 'knowledge-base/org.eclipse.scava.knowledgebase/target/surefire-reports/*.xml', allowEmptyResults: true)
        }
    }
    post {
        success {
            archiveArtifacts 'knowledge-base/org.eclipse.scava.knowledgebase/target/scava.knoledgebase.jar'
        }
      }
    }
  }
  post {
  	always {
  		deleteDir()
  	}
  }
}
