pipeline {
  agent any
  stages {
    stage('Build') {
        stage('Build Knowledge Base') {
          steps {
              dir(path: 'knowledge-base/org.eclipse.scava.knowledgebase/') {
                sh 'mvn validate'
                sh 'mvn compile'
                sh 'mvn test'
              }

            junit(testResults: 'knowledge-base/org.eclipse.scava.knowledgebase/target/surefire-reports/*.xml', allowEmptyResults: true)
          }
        }
      }
    }
  }
}
