/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:51:21 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EmptySink;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.Result;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmptySinkBase_ESTest extends EmptySinkBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      emptySink0.setWorkflow(ghRepoExample0);
      Workflow workflow0 = emptySink0.getWorkflow();
      assertTrue(workflow0.isMaster());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      emptySink0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      Result result0 = new Result();
      // Undeclared exception!
      try { 
        emptySink0.consumeResultsPublisherActual(result0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EmptySinkBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      Workflow workflow0 = emptySink0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      // Undeclared exception!
      try { 
        emptySink0.taskBlocked("\"{[6.+\\U_ZJpMrJ|");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EmptySinkBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      // Undeclared exception!
      try { 
        emptySink0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EmptySinkBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EmptySink emptySink0 = new EmptySink();
      EclipseResultPublisher eclipseResultPublisher0 = emptySink0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }
}
