/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 16:53:29 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepo;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoCounter;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.ResultsPublisher;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GhRepoCounterBase_ESTest extends GhRepoCounterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      // Undeclared exception!
      try { 
        ghRepoCounter0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      ghRepoCounter0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      // Undeclared exception!
      try { 
        ghRepoCounter0.taskBlocked("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      Workflow workflow0 = ghRepoCounter0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      GhRepo ghRepo0 = new GhRepo();
      // Undeclared exception!
      try { 
        ghRepoCounter0.consumeGhReposActual(ghRepo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      ResultsPublisher resultsPublisher0 = ghRepoCounter0.getResultsPublisher();
      assertNull(resultsPublisher0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      ghRepoCounter0.setResultsPublisher((ResultsPublisher) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoCounter0.setWorkflow(ghRepoExample0);
      Workflow workflow0 = ghRepoCounter0.getWorkflow();
      assertSame(workflow0, ghRepoExample0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      EclipseResultPublisher eclipseResultPublisher0 = ghRepoCounter0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }
}
