/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:28:05 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Map;
import java.util.Set;
import org.apache.camel.processor.aggregate.MemoryAggregationRepository;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepo;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoCounter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GhRepoCounter_ESTest extends GhRepoCounter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      GhRepo ghRepo0 = new GhRepo();
      MemoryAggregationRepository memoryAggregationRepository0 = new MemoryAggregationRepository(true);
      Set<String> set0 = memoryAggregationRepository0.getKeys();
      ghRepoCounter0.alreadySeenJobs = set0;
      // Undeclared exception!
      try { 
        ghRepoCounter0.consumeGhRepos(ghRepo0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Collections$UnmodifiableCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      GhRepo ghRepo0 = new GhRepo();
      // Undeclared exception!
      try { 
        ghRepoCounter0.consumeGhRepos(ghRepo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      Set<String> set0 = ghRepoCounter0.getAlreadySeenJobs();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GhRepoCounter ghRepoCounter0 = new GhRepoCounter();
      Map<String, Integer> map0 = ghRepoCounter0.getCommittedRepoMap();
      assertTrue(map0.isEmpty());
  }
}
