/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:21:56 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExampleMasterWorkers;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GhRepoExampleMasterWorkers_ESTest extends GhRepoExampleMasterWorkers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[8];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/Master");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExampleMasterWorkers");
      try { 
        GhRepoExampleMasterWorkers.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GhRepoExampleMasterWorkers ghRepoExampleMasterWorkers0 = new GhRepoExampleMasterWorkers();
  }
}
