/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:02:04 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoSource;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepos;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GhRepoSourceBase_ESTest extends GhRepoSourceBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoSource0.setWorkflow(ghRepoExample0);
      assertEquals(Mode.MASTER, ghRepoExample0.getMode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoSource0.workflow = ghRepoExample0;
      Workflow workflow0 = ghRepoSource0.getWorkflow();
      assertTrue(workflow0.isMaster());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      // Undeclared exception!
      try { 
        ghRepoSource0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoSourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      EclipseResultPublisher eclipseResultPublisher0 = ghRepoSource0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      GhRepos ghRepos0 = ghRepoSource0.getGhRepos();
      assertNull(ghRepos0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      Workflow workflow0 = ghRepoSource0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      // Undeclared exception!
      try { 
        ghRepoSource0.taskBlocked("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoSourceBase");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoSourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      ghRepoSource0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      ghRepoSource0.setGhRepos((GhRepos) null);
  }
}
