/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:14:13 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.jms.JMSException;
import javax.management.remote.JMXPrincipal;
import javax.swing.table.DefaultTableModel;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoSource;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GhRepoExample_ESTest extends GhRepoExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          String[] stringArray0 = new String[0];
          try { 
            GhRepoExample.main(stringArray0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample.run(GhRepoExample.java:51)
             // org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample.main(GhRepoExample.java:19)
             // sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      GhRepoSource ghRepoSource0 = new GhRepoSource();
      ghRepoExample0.ghRepoSource = ghRepoSource0;
      ghRepoExample0.getGhRepoSource();
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "@DHXE78.1";
      try { 
        GhRepoExample.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not read file DHXE78.1: java.io.FileNotFoundException
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "GhRepoSource";
      stringArray0[1] = "S>@ fKtt";
      stringArray0[2] = "%d&v_'`6Hx@c{";
      stringArray0[3] = "amG3";
      stringArray0[4] = "";
      stringArray0[5] = "2V1y$N&(S";
      stringArray0[6] = "nxuu8";
      stringArray0[7] = "EYRzGW_x}!t-;";
      stringArray0[8] = "%.V7dZd-%jf/0]";
      try { 
        GhRepoExample.main(stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          GhRepoExample ghRepoExample0 = new GhRepoExample();
          try { 
            ghRepoExample0.run();
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample.run(GhRepoExample.java:51)
             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          GhRepoExample ghRepoExample0 = new GhRepoExample();
          Mode mode0 = Mode.WORKER;
          ghRepoExample0.setMode(mode0);
          try { 
            ghRepoExample0.run();
            fail("Expecting exception: JMSException");
          
          } catch(JMSException e) {
             //
             // Could not connect to broker URL: tcp://localhost:61616. Reason: java.lang.SecurityException: Security manager blocks (\"java.net.SocketPermission\" \"200.42.42.0:61616\" \"connect,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             // java.net.Socket.connect(Socket.java:584)
             // org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)
             // org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)
             // org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
             // org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169)
             // org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
             // org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
             // org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.EclipseResultPublisher.<init>(EclipseResultPublisher.java:27)
             // org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample.run(GhRepoExample.java:55)
             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.apache.activemq.util.JMSExceptionSupport", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      Vector<Integer> vector0 = new Vector<Integer>();
      DefaultTableModel defaultTableModel0 = new DefaultTableModel(vector0, 105);
      // Undeclared exception!
      try { 
        ghRepoExample0.setTaskInProgess(defaultTableModel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("Ard#%J`8)aElClL");
      // Undeclared exception!
      try { 
        ghRepoExample0.setTaskUnblocked(jMXPrincipal0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoExample0.getEmptySink();
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[9];
      try { 
        GhRepoExample.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoExample0.getGhRepoSource();
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      // Undeclared exception!
      try { 
        ghRepoExample0.setTaskBlocked((Object) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoExample0.getGhRepoCounter();
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoExample0.getGhRepos();
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      ghRepoExample0.excludeTasks(arrayList0);
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      ghRepoExample0.getResultsPublisher();
      assertEquals("GhRepoExample", ghRepoExample0.getName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GhRepoExample ghRepoExample0 = new GhRepoExample();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        ghRepoExample0.setTaskWaiting(object0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepoExample", e);
      }
  }
}
