/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:45:01 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.ghrepo.GhRepo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GhRepo_ESTest extends GhRepo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GhRepo ghRepo0 = new GhRepo();
      ghRepo0.setRepoUrl("d");
      String string0 = ghRepo0.getRepoUrl();
      assertEquals("d", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GhRepo ghRepo0 = new GhRepo();
      ghRepo0.setRepoUrl("");
      String string0 = ghRepo0.getRepoUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GhRepo ghRepo0 = new GhRepo();
      String string0 = ghRepo0.getRepoUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GhRepo ghRepo0 = new GhRepo();
      Object[] objectArray0 = ghRepo0.toObjectArray();
      assertEquals(1, objectArray0.length);
  }
}
