/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:23:11 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.opinionated;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExampleMasterWorkers;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OpinionatedExampleMasterWorkers_ESTest extends OpinionatedExampleMasterWorkers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[7];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/ApplesCounter");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "ApplesCounter");
      try { 
        OpinionatedExampleMasterWorkers.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OpinionatedExampleMasterWorkers opinionatedExampleMasterWorkers0 = new OpinionatedExampleMasterWorkers();
  }
}
