/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:35:58 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.opinionated;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.sql.SQLFeatureNotSupportedException;
import java.util.TreeSet;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.jms.JMSException;
import javax.xml.transform.TransformerException;
import org.apache.camel.model.TransformDefinition;
import org.eclipse.jgit.diff.RawText;
import org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OpinionatedExample_ESTest extends OpinionatedExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      opinionatedExample0.setFavouriteWord("");
      String string0 = opinionatedExample0.getFavouriteWord();
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/OpinionatedExample");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "v22@UOU");
      try { 
        opinionatedExample0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "iV`5[n%yI2|a\"s+U-";
      try { 
        OpinionatedExample.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Was passed main parameter 'iV`5[n%yI2|a\"s+U-' but no main parameter was defined
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "]fHRV4K%~#(";
      stringArray0[2] = "";
      stringArray0[3] = "org.apache.camel.processor.SamplingThrottler$SampleStats";
      stringArray0[4] = "PS^1WZMjd";
      stringArray0[5] = "This CamelContext(";
      stringArray0[6] = "Value of nested property '";
      stringArray0[7] = "dY";
      try { 
        OpinionatedExample.main(stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      try { 
        OpinionatedExample.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          OpinionatedExample opinionatedExample0 = new OpinionatedExample();
          try { 
            opinionatedExample0.run();
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample.run(OpinionatedExample.java:58)
             // sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          OpinionatedExample opinionatedExample0 = new OpinionatedExample();
          Mode mode0 = Mode.WORKER;
          opinionatedExample0.setMode(mode0);
          try { 
            opinionatedExample0.run();
            fail("Expecting exception: JMSException");
          
          } catch(JMSException e) {
             //
             // Could not connect to broker URL: tcp://localhost:61616. Reason: java.lang.SecurityException: Security manager blocks (\"java.net.SocketPermission\" \"200.42.42.0:61616\" \"connect,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             // java.net.Socket.connect(Socket.java:584)
             // org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)
             // org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)
             // org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
             // org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169)
             // org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
             // org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
             // org.eclipse.scava.crossflow.examples.opinionated.EclipseTaskStatusPublisher.<init>(EclipseTaskStatusPublisher.java:28)
             // org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample.run(OpinionatedExample.java:62)
             // sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.apache.activemq.util.JMSExceptionSupport", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      opinionatedExample0.setFavouriteWord("v22@UOU");
      String string0 = opinionatedExample0.getFavouriteWord();
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      // Undeclared exception!
      try { 
        opinionatedExample0.setTaskWaiting((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          String[] stringArray0 = new String[0];
          try { 
            OpinionatedExample.main(stringArray0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample.run(OpinionatedExample.java:58)
             // org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample.main(OpinionatedExample.java:19)
             // sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      byte[] byteArray0 = new byte[9];
      RawText rawText0 = new RawText(byteArray0);
      // Undeclared exception!
      try { 
        opinionatedExample0.setTaskUnblocked(rawText0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      opinionatedExample0.getOccurencesMonitor();
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      SQLFeatureNotSupportedException sQLFeatureNotSupportedException0 = new SQLFeatureNotSupportedException("~M-l kWeQ~{/:W");
      TransformerException transformerException0 = new TransformerException("~M-l kWeQ~{/:W", sQLFeatureNotSupportedException0);
      // Undeclared exception!
      try { 
        opinionatedExample0.setTaskBlocked(transformerException0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      opinionatedExample0.getWords();
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      opinionatedExample0.getFavouriteWord();
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      TransformDefinition transformDefinition0 = new TransformDefinition();
      // Undeclared exception!
      try { 
        opinionatedExample0.setTaskInProgess(transformDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      opinionatedExample0.getWordSource();
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      TreeSet<String> treeSet0 = new TreeSet<String>();
      opinionatedExample0.excludeTasks(treeSet0);
      assertEquals("OpinionatedExample", opinionatedExample0.getName());
  }
}
