/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:17:18 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.opinionated;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.opinionated.Word;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Word_ESTest extends Word_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Word word0 = new Word();
      word0.setW("org.eclipse.scava.crossflow.runtime.Job");
      String string0 = word0.getW();
      assertEquals("org.eclipse.scava.crossflow.runtime.Job", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Word word0 = new Word();
      word0.setW("");
      String string0 = word0.getW();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Word word0 = new Word();
      String string0 = word0.getW();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Word word0 = new Word();
      Object[] objectArray0 = word0.toObjectArray();
      assertEquals(1, objectArray0.length);
  }
}
