/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:25:15 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.opinionated;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.apache.camel.spring.SpringCamelContext;
import org.eclipse.scava.crossflow.examples.opinionated.OpinionatedExample;
import org.eclipse.scava.crossflow.examples.opinionated.WordSource;
import org.eclipse.scava.crossflow.examples.opinionated.Words;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.context.support.ClassPathXmlApplicationContext;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordSourceBase_ESTest extends WordSourceBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      ClassPathXmlApplicationContext classPathXmlApplicationContext0 = new ClassPathXmlApplicationContext();
      SpringCamelContext springCamelContext0 = new SpringCamelContext(classPathXmlApplicationContext0);
      List<String> list0 = springCamelContext0.getLanguageNames();
      wordSource0.words = list0;
      wordSource0.produce();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      // Undeclared exception!
      try { 
        wordSource0.produce();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.WordSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      // Undeclared exception!
      try { 
        wordSource0.taskBlocked("Invalid session state.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.WordSourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      Words words0 = wordSource0.getWords();
      assertNull(words0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      // Undeclared exception!
      try { 
        wordSource0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.WordSourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      OpinionatedExample opinionatedExample0 = new OpinionatedExample();
      wordSource0.setWorkflow(opinionatedExample0);
      Workflow workflow0 = wordSource0.getWorkflow();
      assertSame(workflow0, opinionatedExample0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      wordSource0.setWords((Words) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      Workflow workflow0 = wordSource0.getWorkflow();
      assertNull(workflow0);
  }
}
