/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 16:54:09 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.opinionated;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.camel.component.bean.BeanComponent;
import org.eclipse.scava.crossflow.examples.opinionated.WordSource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordSource_ESTest extends WordSource_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      BeanComponent beanComponent0 = new BeanComponent();
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      Class<String> class0 = String.class;
      List<String> list0 = beanComponent0.resolveAndRemoveReferenceListParameter((Map<String, Object>) hashMap0, "", class0);
      wordSource0.words = list0;
      wordSource0.produce();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WordSource wordSource0 = new WordSource();
      // Undeclared exception!
      try { 
        wordSource0.produce();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.opinionated.WordSource", e);
      }
  }
}
