/*
 * generated by Xtext 2.16.0
 */
package org.eclipse.scava.crossflow.language.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CrossflowRuntimeModule extends AbstractCrossflowRuntimeModule {
}
