/*
 * generated by Xtext 2.16.0
 */
package org.eclipse.scava.crossflow.language.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CrossflowStandaloneSetup extends CrossflowStandaloneSetupGenerated {

	def static void doSetup() {
		new CrossflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
