pipeline {
  agent any
  stages {
    stage('Build Metric Platform') {
      steps {
        dir(path: 'metric-platform/') {
          sh 'mvn clean install -DskipTests'
        }
      }
    }
    stage('Test Metric Platform') {
      steps {
        dir(path: 'metric-platform/') {
          sh 'mvn test integration-test'
        }
      }
    }
  }
}
