<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow" nsURI="http://org.eclipse.scava.workflow" nsPrefix="wf">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eAnnotations source="gmf.diagram">
      <details key="onefile" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//Configuration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="streams" upperBound="-1"
        eType="#//Stream" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingStream" lowerBound="1"
        upperBound="-1" eType="#//Stream" eOpposite="#//Stream/outgoingTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingStream" lowerBound="1"
        upperBound="-1" eType="#//Stream" eOpposite="#//Stream/incomingTasks">
      <eAnnotations source="gmf.link"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskType" lowerBound="1"
        eType="#//TaskTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="broadcastTo" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stream">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/outgoingStream"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/incomingStream">
      <eAnnotations source="gmf.link"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationFullyQualifiedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationEntryPoint"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptedTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteAPICallTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSourceUUID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Struct" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extending" upperBound="-1"
        eType="#//Struct">
      <eAnnotations source="gmf.link"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field">
      <eAnnotations source="gmf.link"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.pattern" value="{0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMany" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskTypes">
    <eLiterals name="source"/>
    <eLiterals name="sink" value="1"/>
    <eLiterals name="map" value="2"/>
    <eLiterals name="flatMap" value="3"/>
    <eLiterals name="filter" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eAnnotations source="gmf.node">
      <details key="label" value="numberOfSlaves,numberOfCoresPerSlave"/>
      <details key="label.pattern" value="Config: NoS:{0}, NoCPS:{1}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSlaves" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfCoresPerSlave"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
</ecore:EPackage>
