from crossflow.runtime import Job


class Project(Job):
    """NOTE: Auto-generated by Type2Class on 2019-12-19T22:43:50.636Z
    Do not edit this class manually
    """

    def __init__(self,
        owner: str = None,
        repo: str = None,
        commit: str = None,
        correlation: Job = None
    ):
        super().__init__()
        self._owner = owner
        self._repo = repo
        self._commit = commit
        if correlation is not None:
            self.correlationId = correlation.correlationId

    @property
    def owner(self) -> str:
        return self._owner

    @owner.setter
    def owner(self, owner: str):
        self._owner = owner

    @property
    def repo(self) -> str:
        return self._repo

    @repo.setter
    def repo(self, repo: str):
        self._repo = repo

    @property
    def commit(self) -> str:
        return self._commit

    @commit.setter
    def commit(self, commit: str):
        self._commit = commit

    def __str__(self):
        return f"Project ( owner={self.owner}, repo={self.repo}, commit={self.commit}, jobId={self.jobId}, correlationId={self.correlationId}, destination={self.destination} )"
