/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:18:59 GMT 2018
 */

package org.eclipse.scava.crossflow.runtime;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import org.eclipse.scava.crossflow.runtime.Cache;
import org.eclipse.scava.crossflow.runtime.Job;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Cache_ESTest extends Cache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.setName("~L'BHJT=l");
      Cache cache0 = new Cache(workflow0);
      Job job0 = new Job();
      job0.correlationId = "(Mg;(_%7}$NE2LQ0 K";
      Job job1 = new Job();
      cache0.jobMap.put("(Mg;(_%7}$NE2LQ0 K", job1);
      // Undeclared exception!
      try { 
        cache0.cache(job0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.name = "";
      Cache cache0 = new Cache(workflow0);
      Job job0 = new Job();
      // Undeclared exception!
      try { 
        cache0.hasCachedOutputs(job0);
        fail("Expecting exception: NoSuchMethodError");
      
      } catch(NoSuchMethodError e) {
         //
         // org.evosuite.runtime.mock.java.util.MockUUID.nameUUIDFromBytes([B)Ljava/util/UUID;
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Job", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.setName("ZoP|yk|-:<XKqRB");
      Cache cache0 = new Cache(workflow0);
      // Undeclared exception!
      try { 
        cache0.getCachedOutputs((Job) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.setName("~L'BHJT=l");
      Cache cache0 = new Cache(workflow0);
      HashMap<String, Job> hashMap0 = cache0.jobMap;
      Job job0 = new Job();
      job0.destination = "~L'BHJT=l";
      hashMap0.put((String) null, job0);
      // Undeclared exception!
      try { 
        cache0.cache(job0);
        fail("Expecting exception: NoSuchMethodError");
      
      } catch(NoSuchMethodError e) {
         //
         // org.evosuite.runtime.mock.java.util.MockUUID.nameUUIDFromBytes([B)Ljava/util/UUID;
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Job", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      Cache cache0 = null;
      try {
        cache0 = new Cache(workflow0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.setName("ZoP|yk|-:<XKqRB");
      Cache cache0 = new Cache(workflow0);
      // Undeclared exception!
      try { 
        cache0.hasCachedOutputs((Job) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.setName("");
      Cache cache0 = new Cache(workflow0);
      Job job0 = new Job();
      cache0.cache(job0);
      assertFalse(job0.isCached());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/@skQ~%GB#=<v`\\j");
      FileSystemHandling.createFolder(evoSuiteFile0);
      Workflow workflow0 = new Workflow();
      workflow0.setName("");
      Cache cache0 = new Cache(workflow0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/@skQ~%GB#=<v`\\j");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "`$l|GenL{03)/+mN");
      Workflow workflow0 = new Workflow();
      workflow0.setName("");
      Cache cache0 = new Cache(workflow0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Workflow workflow0 = new Workflow();
      workflow0.setName("");
      Job job0 = new Job();
      Cache cache0 = new Cache(workflow0);
      // Undeclared exception!
      try { 
        cache0.getCachedOutputs(job0);
        fail("Expecting exception: NoSuchMethodError");
      
      } catch(NoSuchMethodError e) {
         //
         // org.evosuite.runtime.mock.java.util.MockUUID.nameUUIDFromBytes([B)Ljava/util/UUID;
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Job", e);
      }
  }
}
