/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:41:14 GMT 2018
 */

package org.eclipse.scava.crossflow.runtime;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.ModeConverter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModeConverter_ESTest extends ModeConverter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ModeConverter modeConverter0 = new ModeConverter();
      // Undeclared exception!
      try { 
        modeConverter0.convert("WaPhx\"6#rB* ,");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Mode must be 'master' or 'worker' but was 'WaPhx\"6#rB* ,'
         //
         verifyException("org.eclipse.scava.crossflow.runtime.ModeConverter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ModeConverter modeConverter0 = new ModeConverter();
      Mode mode0 = modeConverter0.convert("master");
      assertEquals(Mode.MASTER, mode0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ModeConverter modeConverter0 = new ModeConverter();
      Mode mode0 = modeConverter0.convert("worker");
      assertEquals(Mode.WORKER, mode0);
  }
}
