/**
 *
 * $Id$
 */
package crossflow.validation;


/**
 * A sample validator interface for {@link crossflow.Configuration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigurationValidator {
	boolean validate();

	boolean validateNumberOfWorkers(Integer value);
	boolean validateIsMasterAlsoWorker(Boolean value);
	boolean validateRootPackageName(String value);
	boolean validateProjectName(String value);
}
