/**
 *
 * $Id$
 */
package crossflow.validation;

import crossflow.Stream;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link crossflow.Task}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateInput(EList<Stream> value);
	boolean validateOutput(EList<Stream> value);
	boolean validateParallel(Boolean value);
	boolean validateCached(Boolean value);
}
