/**
 *
 * $Id$
 */
package crossflow.validation;

import crossflow.Configuration;
import crossflow.Field;
import crossflow.Stream;
import crossflow.Task;
import crossflow.Type;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link crossflow.Workflow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowValidator {
	boolean validate();

	boolean validateConfiguration(Configuration value);
	boolean validateName(String value);
	boolean validatePackage(String value);
	boolean validateStreams(EList<Stream> value);
	boolean validateTasks(EList<Task> value);
	boolean validateTypes(EList<Type> value);
	boolean validateParameters(EList<Field> value);
}
