package org.eclipse.scava.crossflow.examples.firstcommitment.csvmdetech;

public interface MdeTechnologyClonedRepoEntriesForAuthorCounterConsumer {
	
	void consumeMdeTechnologyClonedRepoEntriesForAuthorCounterWithNotifications(ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple);
	
}