package org.eclipse.scava.crossflow.examples.firstcommitment.csvmdetech;

public interface MdeTechnologyClonedRepoEntriesForFileCounterConsumer {
	
	void consumeMdeTechnologyClonedRepoEntriesForFileCounterWithNotifications(ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple);
	
}