<?xml version="1.0" encoding="ASCII"?>
<!--
  Copyright (c) 2017 University of Manchester
  
  This program and the accompanying materials are made
  available under the terms of the Eclipse Public License 2.0
  which is available at https://www.eclipse.org/legal/epl-2.0/
  
  SPDX-License-Identifier: EPL-2.0
-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.eclipse.scava.metricprovider.historic.newsgroups.requestsreplies.average.model">
  <eClassifiers xsi:type="ecore:EClass" name="NewsgroupsRequestsRepliesAverageHistoricMetric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageArticlesPerDay">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageRequestsPerDay">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageRepliesPerDay">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
