<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.eclipse.scava.metricprovider.historic.newsgroups.migrationissuesmaracas.model">
  <eClassifiers xsi:type="ecore:EClass" name="NewsgroupMigrationIssueMaracasHistoricMetric">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dailyNewsgroupMigrationMaracasData" upperBound="-1" eType="//DailyNewsgroupMigrationMaracasData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newsgroupMigrationMaracasData" upperBound="-1" eType="//NewsgroupMigrationMaracasData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DailyNewsgroupMigrationMaracasData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newsgroupName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadsId" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfIssues">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewsgroupMigrationMaracasData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newsgroupName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadId">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changesAndMatchingPercentage" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
