/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 19:05:16 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.Animal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Animal_ESTest extends Animal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Animal animal0 = new Animal();
      animal0.setName("4g3.9e.s]J\"g");
      String string0 = animal0.getName();
      assertEquals("4g3.9e.s]J\"g", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Animal animal0 = new Animal();
      animal0.setName("");
      String string0 = animal0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Animal animal0 = new Animal();
      String string0 = animal0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Animal animal0 = new Animal();
      Object[] objectArray0 = animal0.toObjectArray();
      assertEquals(1, objectArray0.length);
  }
}
