/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:20:34 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.AnimalSource;
import org.eclipse.scava.crossflow.examples.firstcommitment.Animals;
import org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnimalSourceBase_ESTest extends AnimalSourceBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      animalSource0.produce();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      Workflow workflow0 = animalSource0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      animalSource0.setAnimals((Animals) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      // Undeclared exception!
      try { 
        animalSource0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.AnimalSourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      Animals animals0 = animalSource0.getAnimals();
      assertNull(animals0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      // Undeclared exception!
      try { 
        animalSource0.taskBlocked("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.AnimalSourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AnimalSource animalSource0 = new AnimalSource();
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      animalSource0.setWorkflow(firstCommitmentExample0);
      Workflow workflow0 = animalSource0.getWorkflow();
      assertTrue(workflow0.isMaster());
  }
}
