/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 16:58:32 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.jms.JMSException;
import org.apache.camel.model.rest.RestOperationParamDefinition;
import org.eclipse.jgit.lib.CommitBuilder;
import org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FirstCommitmentExample_ESTest extends FirstCommitmentExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          String[] stringArray0 = new String[0];
          try { 
            FirstCommitmentExample.main(stringArray0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample.run(FirstCommitmentExample.java:48)
             // org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample.main(FirstCommitmentExample.java:19)
             // sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/FirstCommitmentExample");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      try { 
        firstCommitmentExample0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "XgB=qu+>_fc<q";
      stringArray0[1] = "XgB=qu+>_fc<q";
      stringArray0[2] = "l~''tv}CL";
      try { 
        FirstCommitmentExample.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Was passed main parameter 'XgB=qu+>_fc<q' but no main parameter was defined
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "AnimalSource";
      stringArray0[1] = "";
      stringArray0[2] = "[t]lYb<";
      stringArray0[3] = "8lb4x{yxtSRB";
      stringArray0[4] = "AnimalCounter";
      stringArray0[5] = "mmy";
      stringArray0[6] = "w{QAe!VK|}X^bRnQqN";
      stringArray0[7] = "3<fm0c-Z]D&=";
      try { 
        FirstCommitmentExample.main(stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
          Mode mode0 = Mode.WORKER;
          firstCommitmentExample0.setMode(mode0);
          try { 
            firstCommitmentExample0.run();
            fail("Expecting exception: JMSException");
          
          } catch(JMSException e) {
             //
             // Could not connect to broker URL: tcp://localhost:61616. Reason: java.lang.SecurityException: Security manager blocks (\"java.net.SocketPermission\" \"200.42.42.0:61616\" \"connect,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             // java.net.Socket.connect(Socket.java:584)
             // org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)
             // org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)
             // org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
             // org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169)
             // org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
             // org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
             // org.eclipse.scava.crossflow.examples.firstcommitment.EclipseTaskStatusPublisher.<init>(EclipseTaskStatusPublisher.java:28)
             // org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample.run(FirstCommitmentExample.java:52)
             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.apache.activemq.util.JMSExceptionSupport", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      // Undeclared exception!
      try { 
        firstCommitmentExample0.setTaskWaiting("pD;_JpHBz/8YiI3a");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      firstCommitmentExample0.getAnimalCounter();
      assertEquals("FirstCommitmentExample", firstCommitmentExample0.getName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      firstCommitmentExample0.getAnimalSource();
      assertEquals("FirstCommitmentExample", firstCommitmentExample0.getName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[3];
      try { 
        FirstCommitmentExample.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      CommitBuilder commitBuilder0 = new CommitBuilder();
      // Undeclared exception!
      try { 
        firstCommitmentExample0.setTaskBlocked(commitBuilder0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      // Undeclared exception!
      try { 
        firstCommitmentExample0.setTaskInProgess((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      RestOperationParamDefinition restOperationParamDefinition0 = new RestOperationParamDefinition();
      List<String> list0 = restOperationParamDefinition0.getAllowableValues();
      firstCommitmentExample0.excludeTasks(list0);
      assertEquals("FirstCommitmentExample", firstCommitmentExample0.getName());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      firstCommitmentExample0.getAnimals();
      assertEquals("FirstCommitmentExample", firstCommitmentExample0.getName());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FirstCommitmentExample firstCommitmentExample0 = new FirstCommitmentExample();
      // Undeclared exception!
      try { 
        firstCommitmentExample0.setTaskUnblocked((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.FirstCommitmentExample", e);
      }
  }
}
