/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:03:15 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlTuple;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtensionKeywordStargazersRemoteRepoUrlTuple_ESTest extends ExtensionKeywordStargazersRemoteRepoUrlTuple_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      extensionKeywordStargazersRemoteRepoUrlTuple0.field3 = ";}u=39j9-";
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField3();
      assertEquals(";}u=39j9-", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      Integer integer0 = new Integer(0);
      extensionKeywordStargazersRemoteRepoUrlTuple0.field2 = integer0;
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField2();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      Integer integer0 = new Integer(1);
      extensionKeywordStargazersRemoteRepoUrlTuple0.field2 = integer0;
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField2();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      Integer integer0 = new Integer((-1040));
      extensionKeywordStargazersRemoteRepoUrlTuple0.setField2(integer0);
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField2();
      assertEquals((-1040), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      extensionKeywordStargazersRemoteRepoUrlTuple0.setField1("}q2+Lv#iH&");
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField1();
      assertEquals("}q2+Lv#iH&", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      extensionKeywordStargazersRemoteRepoUrlTuple0.setField1("");
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField1();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      extensionKeywordStargazersRemoteRepoUrlTuple0.field0 = "ZC){&J";
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField0();
      assertEquals("ZC){&J", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      extensionKeywordStargazersRemoteRepoUrlTuple0.setField0("");
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField0();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField1();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      Integer integer0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField2();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField3();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField0();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      extensionKeywordStargazersRemoteRepoUrlTuple0.setField3("");
      String string0 = extensionKeywordStargazersRemoteRepoUrlTuple0.getField3();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      Object[] objectArray0 = extensionKeywordStargazersRemoteRepoUrlTuple0.toObjectArray();
      assertEquals(4, objectArray0.length);
  }
}
