/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:42:25 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersTuple;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtensionKeywordStargazersTuple_ESTest extends ExtensionKeywordStargazersTuple_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      Integer integer0 = new Integer(0);
      extensionKeywordStargazersTuple0.setField2(integer0);
      Integer integer1 = extensionKeywordStargazersTuple0.getField2();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      Integer integer0 = Integer.getInteger("41[", (-1752));
      extensionKeywordStargazersTuple0.setField2(integer0);
      Integer integer1 = extensionKeywordStargazersTuple0.getField2();
      assertEquals((-1752), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      extensionKeywordStargazersTuple0.setField1("");
      String string0 = extensionKeywordStargazersTuple0.getField1();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      extensionKeywordStargazersTuple0.field0 = "41[";
      String string0 = extensionKeywordStargazersTuple0.getField0();
      assertEquals("41[", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      Integer integer0 = extensionKeywordStargazersTuple0.getField2();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      String string0 = extensionKeywordStargazersTuple0.getField0();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      String string0 = extensionKeywordStargazersTuple0.getField1();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      extensionKeywordStargazersTuple0.setField1("org.eclipse.scava.crossflow.runtime.Job");
      String string0 = extensionKeywordStargazersTuple0.getField1();
      assertEquals("org.eclipse.scava.crossflow.runtime.Job", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      Integer integer0 = new Integer(2);
      extensionKeywordStargazersTuple0.setField2(integer0);
      Integer integer1 = extensionKeywordStargazersTuple0.getField2();
      assertEquals(2, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      Object[] objectArray0 = extensionKeywordStargazersTuple0.toObjectArray();
      assertEquals(3, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExtensionKeywordStargazersTuple extensionKeywordStargazersTuple0 = new ExtensionKeywordStargazersTuple();
      extensionKeywordStargazersTuple0.setField0("");
      String string0 = extensionKeywordStargazersTuple0.getField0();
      assertEquals("", string0);
  }
}
