/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:28:22 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordTuple;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtensionKeywordTuple_ESTest extends ExtensionKeywordTuple_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      extensionKeywordTuple0.setField1("V3Vhnk@8gW28G(Lj");
      String string0 = extensionKeywordTuple0.getField1();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      extensionKeywordTuple0.setField1("");
      String string0 = extensionKeywordTuple0.getField1();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      extensionKeywordTuple0.setField0("sgE9Da%");
      String string0 = extensionKeywordTuple0.getField0();
      assertEquals("sgE9Da%", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      String string0 = extensionKeywordTuple0.getField0();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      Object[] objectArray0 = extensionKeywordTuple0.toObjectArray();
      assertEquals(2, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      String string0 = extensionKeywordTuple0.getField1();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      extensionKeywordTuple0.setField0("");
      String string0 = extensionKeywordTuple0.getField0();
      assertEquals("", string0);
  }
}
