/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 16:49:43 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple_ESTest extends ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField3("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple");
      assertEquals("00000000-0100-4000-8200-000003000000", extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = new Integer(0);
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.field4 = integer0;
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField4();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = new Integer(3268);
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField4(integer0);
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField4();
      assertEquals(3268, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = new Integer((-2573));
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField4(integer0);
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField4();
      assertEquals((-2573), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.field3 = "dHYE(oQ.=lD3`pK";
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField3();
      assertEquals("dHYE(oQ.=lD3`pK", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.field3 = "";
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField3();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = new Integer(0);
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.field2 = integer0;
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField2();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = new Integer(2);
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField2(integer0);
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField2();
      assertEquals(2, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = new Integer((-2593));
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField2(integer0);
      Integer integer1 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField2();
      assertEquals((-2593), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField1(".sr(2{F|4s$CTQ");
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField1();
      assertEquals(".sr(2{F|4s$CTQ", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField1("");
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField1();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.field0 = "0C.q$SF";
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField0();
      assertEquals("0C.q$SF", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.setField0("");
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField0();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField1();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField0();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      String string0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField3();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField4();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Integer integer0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.getField2();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      Object[] objectArray0 = extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.toObjectArray();
      assertEquals(5, objectArray0.length);
  }
}
