/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:36:14 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCountEntries;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCounter;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoAuthorCounterBase_ESTest extends MdeTechnologyRepoAuthorCounterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoAuthorCounter0.setWorkflow(mdeTechnologyExample0);
      Workflow workflow0 = mdeTechnologyRepoAuthorCounter0.getWorkflow();
      assertSame(workflow0, mdeTechnologyExample0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoAuthorCounter0.taskBlocked("Qe}");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      mdeTechnologyRepoAuthorCounter0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologyRepoAuthorCounter0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      MdeTechnologyRepoAuthorCountEntries mdeTechnologyRepoAuthorCountEntries0 = mdeTechnologyRepoAuthorCounter0.getMdeTechnologyRepoAuthorCountEntries();
      assertNull(mdeTechnologyRepoAuthorCountEntries0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoAuthorCounter0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      Workflow workflow0 = mdeTechnologyRepoAuthorCounter0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoAuthorCounter0.consumeMdeTechnologyClonedRepoEntriesForAuthorCounterActual(extensionKeywordStargazersRemoteRepoUrlTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MdeTechnologyRepoAuthorCounter mdeTechnologyRepoAuthorCounter0 = new MdeTechnologyRepoAuthorCounter();
      mdeTechnologyRepoAuthorCounter0.setMdeTechnologyRepoAuthorCountEntries((MdeTechnologyRepoAuthorCountEntries) null);
  }
}
