/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:04:53 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologies;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologySource;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologySourceBase_ESTest extends MdeTechnologySourceBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologySource0.setWorkflow(mdeTechnologyExample0);
      Workflow workflow0 = mdeTechnologySource0.getWorkflow();
      assertEquals(Mode.MASTER, workflow0.getMode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      MdeTechnologies mdeTechnologies0 = mdeTechnologySource0.getMdeTechnologies();
      assertNull(mdeTechnologies0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      // Undeclared exception!
      try { 
        mdeTechnologySource0.produce();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologySource", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      // Undeclared exception!
      try { 
        mdeTechnologySource0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologySourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      Workflow workflow0 = mdeTechnologySource0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologySource0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      mdeTechnologySource0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      // Undeclared exception!
      try { 
        mdeTechnologySource0.taskBlocked("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologySourceBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      mdeTechnologySource0.setMdeTechnologies((MdeTechnologies) null);
  }
}
