/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:40:06 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoEntries;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFetcher;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoFetcherBase_ESTest extends MdeTechnologyRepoFetcherBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoFetcher0.workflow = mdeTechnologyExample0;
      Workflow workflow0 = mdeTechnologyRepoFetcher0.getWorkflow();
      assertEquals(Mode.MASTER, workflow0.getMode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      mdeTechnologyRepoFetcher0.setMdeTechnologyRepoEntries((MdeTechnologyRepoEntries) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologyRepoFetcher0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFetcher0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFetcherBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoFetcher0.setWorkflow(mdeTechnologyExample0);
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFetcher0.taskBlocked("|- ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFetcherBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      mdeTechnologyRepoFetcher0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      Workflow workflow0 = mdeTechnologyRepoFetcher0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      ExtensionKeywordTuple extensionKeywordTuple0 = new ExtensionKeywordTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFetcher0.consumeMdeTechnologiesActual(extensionKeywordTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFetcherBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MdeTechnologyRepoFetcher mdeTechnologyRepoFetcher0 = new MdeTechnologyRepoFetcher();
      MdeTechnologyRepoEntries mdeTechnologyRepoEntries0 = mdeTechnologyRepoFetcher0.getMdeTechnologyRepoEntries();
      assertNull(mdeTechnologyRepoEntries0);
  }
}
