/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:06:45 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.util.Map;
import java.util.Set;
import org.apache.camel.impl.CompositeRegistry;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoFileCounter_ESTest extends MdeTechnologyRepoFileCounter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[8];
      FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        MdeTechnologyRepoFileCounter.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      CompositeRegistry compositeRegistry0 = new CompositeRegistry();
      Class<String> class0 = String.class;
      Set<String> set0 = compositeRegistry0.findByType(class0);
      mdeTechnologyRepoFileCounter0.alreadySeenJobs = set0;
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCounter0.consumeMdeTechnologyClonedRepoEntriesForFileCounter(extensionKeywordStargazersRemoteRepoUrlTuple0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCounter0.consumeMdeTechnologyClonedRepoEntriesForFileCounter(extensionKeywordStargazersRemoteRepoUrlTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      Map<String, Integer> map0 = mdeTechnologyRepoFileCounter0.getCommittedRepoMap();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      Set<String> set0 = mdeTechnologyRepoFileCounter0.getAlreadySeenJobs();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[6];
      MdeTechnologyRepoFileCounter.main(stringArray0);
      assertEquals(6, stringArray0.length);
  }
}
