/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:53:11 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCountEntries;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCounter;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoOwnerPopularityCounterBase_ESTest extends MdeTechnologyRepoOwnerPopularityCounterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoOwnerPopularityCounter0.workflow = mdeTechnologyExample0;
      Workflow workflow0 = mdeTechnologyRepoOwnerPopularityCounter0.getWorkflow();
      assertSame(workflow0, mdeTechnologyExample0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      mdeTechnologyRepoOwnerPopularityCounter0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoOwnerPopularityCounter0.consumeMdeTechnologyClonedRepoEntriesForOwnerPopularityCounterActual(extensionKeywordStargazersRemoteRepoUrlTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologyRepoOwnerPopularityCounter0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoOwnerPopularityCounter0.taskBlocked("z?hMx$j!1uU-)[");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoOwnerPopularityCounter0.setWorkflow(mdeTechnologyExample0);
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      Workflow workflow0 = mdeTechnologyRepoOwnerPopularityCounter0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      mdeTechnologyRepoOwnerPopularityCounter0.setMdeTechnologyRepoOwnerPopularityCountEntries((MdeTechnologyRepoOwnerPopularityCountEntries) null);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoOwnerPopularityCounter0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCounter mdeTechnologyRepoOwnerPopularityCounter0 = new MdeTechnologyRepoOwnerPopularityCounter();
      MdeTechnologyRepoOwnerPopularityCountEntries mdeTechnologyRepoOwnerPopularityCountEntries0 = mdeTechnologyRepoOwnerPopularityCounter0.getMdeTechnologyRepoOwnerPopularityCountEntries();
      assertNull(mdeTechnologyRepoOwnerPopularityCountEntries0);
  }
}
