/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:13:17 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCountPrinter;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoAuthorCountPrinterBase_ESTest extends MdeTechnologyRepoAuthorCountPrinterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoAuthorCountPrinter0.setWorkflow(mdeTechnologyExample0);
      Workflow workflow0 = mdeTechnologyRepoAuthorCountPrinter0.getWorkflow();
      assertEquals("MdeTechnologyExample", workflow0.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      mdeTechnologyRepoAuthorCountPrinter0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoAuthorCountPrinter0.consumeMdeTechnologyRepoAuthorCountEntriesActual((ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCountPrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologyRepoAuthorCountPrinter0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoAuthorCountPrinter0.setWorkflow(mdeTechnologyExample0);
      Mode mode0 = Mode.WORKER;
      mdeTechnologyExample0.setMode(mode0);
      Workflow workflow0 = mdeTechnologyRepoAuthorCountPrinter0.getWorkflow();
      assertSame(workflow0, mdeTechnologyExample0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoAuthorCountPrinter0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCountPrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoAuthorCountPrinter0.taskBlocked("u|EO_");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoAuthorCountPrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologyRepoAuthorCountPrinter mdeTechnologyRepoAuthorCountPrinter0 = new MdeTechnologyRepoAuthorCountPrinter();
      Workflow workflow0 = mdeTechnologyRepoAuthorCountPrinter0.getWorkflow();
      assertNull(workflow0);
  }
}
