/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:36:37 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCountPrinter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoOwnerPopularityCountPrinter_ESTest extends MdeTechnologyRepoOwnerPopularityCountPrinter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCountPrinter mdeTechnologyRepoOwnerPopularityCountPrinter0 = new MdeTechnologyRepoOwnerPopularityCountPrinter();
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoOwnerPopularityCountPrinter0.workflow = mdeTechnologyExample0;
      mdeTechnologyRepoOwnerPopularityCountPrinter0.consumeMdeTechnologyRepoOwnerPopularityCountEntries(extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0);
      assertFalse(extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0.isCached());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoOwnerPopularityCountPrinter mdeTechnologyRepoOwnerPopularityCountPrinter0 = new MdeTechnologyRepoOwnerPopularityCountPrinter();
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoOwnerPopularityCountPrinter0.consumeMdeTechnologyRepoOwnerPopularityCountEntries(extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoOwnerPopularityCountPrinter", e);
      }
  }
}
