/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:41:53 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCountPrinter;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoFileCountPrinterBase_ESTest extends MdeTechnologyRepoFileCountPrinterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      Mode mode0 = Mode.WORKER;
      mdeTechnologyExample0.setMode(mode0);
      mdeTechnologyRepoFileCountPrinter0.setWorkflow(mdeTechnologyExample0);
      Workflow workflow0 = mdeTechnologyRepoFileCountPrinter0.getWorkflow();
      assertEquals("MdeTechnologyExample", workflow0.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologyRepoFileCountPrinter0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoFileCountPrinter0.setWorkflow(mdeTechnologyExample0);
      Workflow workflow0 = mdeTechnologyRepoFileCountPrinter0.getWorkflow();
      assertSame(workflow0, mdeTechnologyExample0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      mdeTechnologyRepoFileCountPrinter0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCountPrinter0.taskBlocked((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCountPrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      Workflow workflow0 = mdeTechnologyRepoFileCountPrinter0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCountPrinter0.consumeMdeTechnologyRepoFileCountEntriesActual(extensionKeywordStargazersRemoteRepoUrlLocalRepoPathTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCountPrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCountPrinter0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCountPrinterBase", e);
      }
  }
}
