/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:55:42 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.jms.JMSException;
import javax.management.remote.JMXPrincipal;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoCloner;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCountPrinter;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounter;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologySource;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.xml.sax.SAXParseException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyExample_ESTest extends MdeTechnologyExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      MdeTechnologySource mdeTechnologySource0 = new MdeTechnologySource();
      mdeTechnologyExample0.mdeTechnologySource = mdeTechnologySource0;
      mdeTechnologyExample0.getMdeTechnologySource();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      mdeTechnologyExample0.mdeTechnologyRepoFileCounter = mdeTechnologyRepoFileCounter0;
      mdeTechnologyExample0.getMdeTechnologyRepoFileCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      MdeTechnologyRepoFileCountPrinter mdeTechnologyRepoFileCountPrinter0 = new MdeTechnologyRepoFileCountPrinter();
      mdeTechnologyExample0.mdeTechnologyRepoFileCountPrinter = mdeTechnologyRepoFileCountPrinter0;
      mdeTechnologyExample0.getMdeTechnologyRepoFileCountPrinter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      MdeTechnologyRepoCloner mdeTechnologyRepoCloner0 = new MdeTechnologyRepoCloner();
      mdeTechnologyExample0.mdeTechnologyRepoCloner = mdeTechnologyRepoCloner0;
      mdeTechnologyExample0.getMdeTechnologyRepoCloner();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/MdeTechnologyExample");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "TOYt5<f");
      try { 
        mdeTechnologyExample0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "V=Vb*cQQ";
      try { 
        MdeTechnologyExample.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Was passed main parameter 'V=Vb*cQQ' but no main parameter was defined
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "D:B5LiK\"l_";
      stringArray0[1] = "MdeTechnologyRepoOwnerPopularityCounter";
      stringArray0[2] = "";
      stringArray0[3] = "MdeTechnologyRepoOwnerPopularityCounter";
      stringArray0[4] = " of type:";
      stringArray0[5] = "";
      stringArray0[6] = "?>A^-'_)daBx";
      stringArray0[7] = "ZA^\"_Q7;^;#:T";
      try { 
        MdeTechnologyExample.main(stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      try { 
        MdeTechnologyExample.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
          try { 
            mdeTechnologyExample0.run();
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample.run(MdeTechnologyExample.java:63)
             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
          Mode mode0 = Mode.WORKER;
          mdeTechnologyExample0.setMode(mode0);
          try { 
            mdeTechnologyExample0.run();
            fail("Expecting exception: JMSException");
          
          } catch(JMSException e) {
             //
             // Could not connect to broker URL: tcp://localhost:61616. Reason: java.lang.SecurityException: Security manager blocks (\"java.net.SocketPermission\" \"200.42.42.0:61616\" \"connect,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             // java.net.Socket.connect(Socket.java:584)
             // org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)
             // org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)
             // org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
             // org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169)
             // org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
             // org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
             // org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher.<init>(EclipseResultPublisher.java:27)
             // org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample.run(MdeTechnologyExample.java:67)
             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.apache.activemq.util.JMSExceptionSupport", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyClonedRepoEntriesForOwnerPopularityCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoFileCountPrinter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      SAXParseException sAXParseException0 = new SAXParseException((String) null, "HzS&JufL,B#c!|H>z", "HzS&JufL,B#c!|H>z", (-1), (-1));
      // Undeclared exception!
      try { 
        mdeTechnologyExample0.setTaskInProgess(sAXParseException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      // Undeclared exception!
      try { 
        mdeTechnologyExample0.setTaskBlocked((Object) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyClonedRepoEntriesForAuthorCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoAuthorCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoCloner();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoFileCountEntries();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      // Undeclared exception!
      try { 
        mdeTechnologyExample0.setTaskUnblocked((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologySource();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoEntries();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoAuthorCountEntries();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.excludeTasks((Collection<String>) null);
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoOwnerPopularityCountPrinter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoAuthorCountPrinter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyClonedRepoEntriesForFileCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologies();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoOwnerPopularityCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("MdeTechnologyExample");
      // Undeclared exception!
      try { 
        mdeTechnologyExample0.setTaskWaiting(jMXPrincipal0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoFileCounter();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoFetcher();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.getMdeTechnologyRepoOwnerPopularityCountEntries();
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          String[] stringArray0 = new String[0];
          try { 
            MdeTechnologyExample.main(stringArray0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample.run(MdeTechnologyExample.java:63)
             // org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample.main(MdeTechnologyExample.java:19)
             // sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
