/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 16:56:07 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.firstcommitment.mdetech;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.ExtensionKeywordStargazersRemoteRepoUrlTuple;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyExample;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCountEntries;
import org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounter;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MdeTechnologyRepoFileCounterBase_ESTest extends MdeTechnologyRepoFileCounterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      ExtensionKeywordStargazersRemoteRepoUrlTuple extensionKeywordStargazersRemoteRepoUrlTuple0 = new ExtensionKeywordStargazersRemoteRepoUrlTuple();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCounter0.consumeMdeTechnologyClonedRepoEntriesForFileCounterActual(extensionKeywordStargazersRemoteRepoUrlTuple0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyRepoFileCounter0.setWorkflow(mdeTechnologyExample0);
      Workflow workflow0 = mdeTechnologyRepoFileCounter0.getWorkflow();
      assertEquals(Mode.MASTER, workflow0.getMode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      Workflow workflow0 = mdeTechnologyRepoFileCounter0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      MdeTechnologyRepoFileCountEntries mdeTechnologyRepoFileCountEntries0 = mdeTechnologyRepoFileCounter0.getMdeTechnologyRepoFileCountEntries();
      assertNull(mdeTechnologyRepoFileCountEntries0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      MdeTechnologyExample mdeTechnologyExample0 = new MdeTechnologyExample();
      mdeTechnologyExample0.mdeTechnologyRepoFileCounter = mdeTechnologyRepoFileCounter0;
      mdeTechnologyExample0.mdeTechnologyRepoFileCounter.setMdeTechnologyRepoFileCountEntries((MdeTechnologyRepoFileCountEntries) null);
      assertEquals("MdeTechnologyExample", mdeTechnologyExample0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCounter0.taskBlocked("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      EclipseResultPublisher eclipseResultPublisher0 = mdeTechnologyRepoFileCounter0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      mdeTechnologyRepoFileCounter0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MdeTechnologyRepoFileCounter mdeTechnologyRepoFileCounter0 = new MdeTechnologyRepoFileCounter();
      // Undeclared exception!
      try { 
        mdeTechnologyRepoFileCounter0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.firstcommitment.mdetech.MdeTechnologyRepoFileCounterBase", e);
      }
  }
}
