// see: https://jenkins.io/doc/pipeline/examples/#artifactory-maven-build
node {
    // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "SERVER_ID"
    // Create an Artifactory Maven instance.
    def rtMaven = Artifactory.newMavenBuild()
    def buildInfo

    stage('Clone sources') {
        git url: 'https://github.com/crossminer/crossflow.git'
    }

    stage('Artifactory configuration') {
        // Tool name from Jenkins configuration
        rtMaven.tool = "Maven-3.3.9"
        // Set Artifactory repositories for dependencies resolution and artifacts deployment.
        rtMaven.deployer releaseRepo:'libs-release-local', snapshotRepo:'libs-snapshot-local', server: server
        rtMaven.resolver releaseRepo:'libs-release', snapshotRepo:'libs-snapshot', server: server
    }

    stage('Maven build') {
        buildInfo = rtMaven.run pom: 'workflow/pom.xml', goals: 'clean install -DskipTests=true'
    }

    //stage('Maven test') {
    //    buildInfo = rtMaven.run pom: 'workflow/pom.xml', goals: 'test'
    //}

    stage('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}
