pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '1'))
  }
  stages {
    stage('Build Crossflow') {
      steps {
        dir(path: 'crossflow/') {
          sh 'mvn clean package'
        }
      }
    }
  }
  post {
    success {
      archiveArtifacts 'crossflow/**/target/*.jar'
    }
    always {
	  	deleteDir()
		}
  }
}
