<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="restmule" nsURI="restmule" nsPrefix="restmule">
  <eClassifiers xsi:type="ecore:EDataType" name="ETimeUnit" instanceClassName="java.util.concurrent.TimeUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="API">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiHost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" eType="#//FormatEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" eType="#//FormatEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoints" upperBound="-1"
        eType="#//Endpoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageWrapper" eType="#//Wrapper"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ratePolicy" eType="#//RatePolicy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pagination" eType="#//PaginationPolicy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auth" lowerBound="1" upperBound="-1"
        eType="#//Auth" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RatePolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reset" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remaining" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" upperBound="-1"
        eType="#//RatePolicyScope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RatePolicyScope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//RatePolicy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1"
        eType="#//Request" eOpposite="#//Request/scope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auths" upperBound="-1"
        eType="#//Auth" eOpposite="#//Auth/rateLimits"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Auth" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rateLimits" upperBound="-1"
        eType="#//Policy" eOpposite="#//Policy/auths"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoAuth" eSuperTypes="#//Auth"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicAuth" eSuperTypes="#//Auth"/>
  <eClassifiers xsi:type="ecore:EClass" name="OAuth" eSuperTypes="#//Auth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginationPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="increment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPerIteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perIteration" eType="#//RequestParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//RequestParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" eType="#//ResponseHeader"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PaginationEnum">
    <eLiterals name="PAGE_NUMBER"/>
    <eLiterals name="LIMIT_OFFSET" value="1"/>
    <eLiterals name="LINK_HEADER" value="2"/>
    <eLiterals name="CURSOR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1"
        eType="#//Request" containment="true" eOpposite="#//Request/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//MethodEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Endpoint"
        eOpposite="#//Endpoint/requests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//RatePolicyScope"
        eOpposite="#//RatePolicyScope/requests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//RequestParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" lowerBound="1"
        upperBound="-1" eType="#//Response" containment="true" eOpposite="#//Response/request"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageWrapped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//Request"
        eOpposite="#//Request/responses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" upperBound="-1"
        eType="#//ResponseHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseHeader" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SimpleType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestParameter" abstract="true" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//RequestParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SimpleType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestHeader" eSuperTypes="#//RequestParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SimpleType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//RequestParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SimpleType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//RequestParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wrapper" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incompleteLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//ListType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//SimpleType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedObjects" upperBound="-1"
        eType="#//ObjectType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listFields" upperBound="-1"
        eType="#//ListType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndefinedType" eSuperTypes="#//SimpleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TInteger" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TLong" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFloat" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TDouble" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minExclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TBoolean" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TString" eSuperTypes="#//SimpleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TFormattedString" eSuperTypes="#//TString">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TDate" eSuperTypes="#//TFormattedString"/>
  <eClassifiers xsi:type="ecore:EClass" name="TDateTime" eSuperTypes="#//TFormattedString"/>
  <eClassifiers xsi:type="ecore:EClass" name="TByte" eSuperTypes="#//TFormattedString"/>
  <eClassifiers xsi:type="ecore:EClass" name="TBinary" eSuperTypes="#//TFormattedString"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FormatEnum">
    <eLiterals name="XML"/>
    <eLiterals name="JSON" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MethodEnum">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
  </eClassifiers>
</ecore:EPackage>
