/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 19:07:15 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.addition;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.addition.Adder;
import org.eclipse.scava.crossflow.examples.addition.AdditionExample;
import org.eclipse.scava.crossflow.examples.addition.AdditionResults;
import org.eclipse.scava.crossflow.examples.addition.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.addition.NumberPair;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AdderBase_ESTest extends AdderBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Adder adder0 = new Adder();
      AdditionResults additionResults0 = adder0.getAdditionResults();
      assertNull(additionResults0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Adder adder0 = new Adder();
      NumberPair numberPair0 = new NumberPair();
      // Undeclared exception!
      try { 
        adder0.consumeAdditionsActual(numberPair0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdderBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Adder adder0 = new Adder();
      // Undeclared exception!
      try { 
        adder0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdderBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Adder adder0 = new Adder();
      EclipseResultPublisher eclipseResultPublisher0 = adder0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Adder adder0 = new Adder();
      adder0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Adder adder0 = new Adder();
      Workflow workflow0 = adder0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Adder adder0 = new Adder();
      adder0.setAdditionResults((AdditionResults) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Adder adder0 = new Adder();
      AdditionExample additionExample0 = new AdditionExample();
      adder0.setWorkflow(additionExample0);
      Workflow workflow0 = adder0.getWorkflow();
      assertSame(workflow0, additionExample0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Adder adder0 = new Adder();
      // Undeclared exception!
      try { 
        adder0.taskBlocked("This reverts commit ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdderBase", e);
      }
  }
}
