/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:58:15 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.addition;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.addition.AdditionExampleMasterWorker;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AdditionExampleMasterWorker_ESTest extends AdditionExampleMasterWorker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/Master-00000000-0100-4000-8200-000003000000");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      String[] stringArray0 = new String[7];
      try { 
        AdditionExampleMasterWorker.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdditionExampleMasterWorker additionExampleMasterWorker0 = new AdditionExampleMasterWorker();
  }
}
