/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:49:06 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.addition;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.sql.SQLTimeoutException;
import java.util.Collection;
import java.util.Vector;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.jms.JMSException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.camel.component.jms.JmsEndpoint;
import org.apache.camel.converter.stream.InputStreamCache;
import org.eclipse.scava.crossflow.examples.addition.AdditionExample;
import org.eclipse.scava.crossflow.examples.addition.NumberPairSource;
import org.eclipse.scava.crossflow.runtime.Mode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.xml.sax.SAXParseException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AdditionExample_ESTest extends AdditionExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          String[] stringArray0 = new String[0];
          try { 
            AdditionExample.main(stringArray0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.net.SocketPermission\" \"localhost:61616\" \"listen,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
             // java.net.ServerSocket.bind(ServerSocket.java:374)
             // java.net.ServerSocket.<init>(ServerSocket.java:237)
             // javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
             // org.apache.activemq.transport.tcp.TcpTransportServer.bind(TcpTransportServer.java:143)
             // org.apache.activemq.transport.tcp.TcpTransportFactory.doBind(TcpTransportFactory.java:62)
             // org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
             // org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2520)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:339)
             // org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:329)
             // org.eclipse.scava.crossflow.examples.addition.AdditionExample.run(AdditionExample.java:51)
             // org.eclipse.scava.crossflow.examples.addition.AdditionExample.main(AdditionExample.java:19)
             // sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      NumberPairSource numberPairSource0 = new NumberPairSource();
      additionExample0.numberPairSource = numberPairSource0;
      additionExample0.getNumberPairSource();
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("crossflow-cache/AdditionExample");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      try { 
        additionExample0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.runtime.Cache", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "Cannot access Collection of type [";
      stringArray0[1] = " p `/%w/H'3s#}8e<0";
      stringArray0[2] = "_3y";
      stringArray0[3] = "VGO2]t^IS]Ypx8vl2";
      stringArray0[4] = "%,[BV(8]~}BM;Z-";
      try { 
        AdditionExample.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Was passed main parameter 'Cannot access Collection of type [' but no main parameter was defined
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "org.eclipse.jgit.api.errors.CheckoutConflictException";
      stringArray0[1] = "P/lB^(wI0tr0Bh0C";
      stringArray0[2] = "?_H.u^-.9LuN45v";
      stringArray0[3] = "";
      stringArray0[4] = "n0ZN4N,+;5R";
      stringArray0[5] = "den$Y";
      stringArray0[6] = "C|<";
      stringArray0[7] = "";
      stringArray0[8] = "NumberPairSource";
      try { 
        AdditionExample.main(stringArray0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          AdditionExample additionExample0 = new AdditionExample();
          Mode mode0 = Mode.WORKER;
          additionExample0.setMode(mode0);
          try { 
            additionExample0.run();
            fail("Expecting exception: JMSException");
          
          } catch(JMSException e) {
             //
             // Could not connect to broker URL: tcp://localhost:61616. Reason: java.lang.SecurityException: Security manager blocks (\"java.net.SocketPermission\" \"200.42.42.0:61616\" \"connect,resolve\")
             // java.lang.Thread.getStackTrace(Thread.java:1559)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkConnect(SecurityManager.java:1051)
             // java.net.Socket.connect(Socket.java:584)
             // org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)
             // org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)
             // org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
             // org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169)
             // org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354)
             // org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
             // org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
             // org.eclipse.scava.crossflow.examples.addition.EclipseResultPublisher.<init>(EclipseResultPublisher.java:27)
             // org.eclipse.scava.crossflow.examples.addition.AdditionExample.run(AdditionExample.java:55)
             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:748)
             //
             verifyException("org.apache.activemq.util.JMSExceptionSupport", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      Vector<JTable> vector0 = new Vector<JTable>();
      DefaultTableModel defaultTableModel0 = new DefaultTableModel(vector0, 0);
      // Undeclared exception!
      try { 
        additionExample0.setTaskWaiting(defaultTableModel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdditionExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      SQLTimeoutException sQLTimeoutException0 = new SQLTimeoutException("");
      SAXParseException sAXParseException0 = new SAXParseException("", "", "Could not unregister Route MBean", 1, (-2465), sQLTimeoutException0);
      // Undeclared exception!
      try { 
        additionExample0.setTaskBlocked(sAXParseException0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdditionExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      additionExample0.excludeTasks((Collection<String>) null);
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      additionExample0.getAdditionResults();
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      additionExample0.getAdditions();
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      byte[] byteArray0 = new byte[23];
      InputStreamCache inputStreamCache0 = new InputStreamCache(byteArray0);
      // Undeclared exception!
      try { 
        additionExample0.setTaskInProgess(inputStreamCache0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdditionExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[5];
      try { 
        AdditionExample.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.beust.jcommander.JCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      additionExample0.getPrinter();
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      additionExample0.getAdder();
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      JmsEndpoint jmsEndpoint0 = new JmsEndpoint("", "Md-P]");
      // Undeclared exception!
      try { 
        additionExample0.setTaskUnblocked(jmsEndpoint0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.AdditionExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      additionExample0.getNumberPairSource();
      assertEquals("AdditionExample", additionExample0.getName());
  }
}
