/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 18:06:13 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.addition;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.scava.crossflow.examples.addition.Number;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Number_ESTest extends Number_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Number number0 = new Number();
      number0.setN(1407);
      int int0 = number0.getN();
      assertEquals(1407, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Number number0 = new Number();
      int int0 = number0.getN();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Number number0 = new Number();
      number0.setN((-1));
      int int0 = number0.getN();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Number number0 = new Number();
      number0.toObjectArray();
      assertEquals(0, number0.getN());
  }
}
