/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 23 17:33:27 GMT 2018
 */

package org.eclipse.scava.crossflow.examples.addition;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.scava.crossflow.examples.addition.AdditionExample;
import org.eclipse.scava.crossflow.examples.addition.EclipseResultPublisher;
import org.eclipse.scava.crossflow.examples.addition.Number;
import org.eclipse.scava.crossflow.examples.addition.Printer;
import org.eclipse.scava.crossflow.runtime.Workflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrinterBase_ESTest extends PrinterBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdditionExample additionExample0 = new AdditionExample();
      Printer printer0 = new Printer();
      printer0.workflow = additionExample0;
      Workflow workflow0 = printer0.getWorkflow();
      assertTrue(workflow0.isMaster());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Printer printer0 = new Printer();
      EclipseResultPublisher eclipseResultPublisher0 = printer0.getEclipseResultPublisher();
      assertNull(eclipseResultPublisher0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Printer printer0 = new Printer();
      // Undeclared exception!
      try { 
        printer0.taskUnblocked();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.PrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Printer printer0 = new Printer();
      // Undeclared exception!
      try { 
        printer0.taskBlocked("sPDLgl#");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.PrinterBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Printer printer0 = new Printer();
      Workflow workflow0 = printer0.getWorkflow();
      assertNull(workflow0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Printer printer0 = new Printer();
      AdditionExample additionExample0 = new AdditionExample();
      printer0.setWorkflow(additionExample0);
      assertEquals("AdditionExample", additionExample0.getName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Printer printer0 = new Printer();
      printer0.setEclipseResultPublisher((EclipseResultPublisher) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Printer printer0 = new Printer();
      // Undeclared exception!
      try { 
        printer0.consumeAdditionResultsActual((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.scava.crossflow.examples.addition.PrinterBase", e);
      }
  }
}
