<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.eclipse.scava.metricprovider.historic.bugs.migrationissuesmaracas.model">
  <eClassifiers xsi:type="ecore:EClass" name="BugTrackerMigrationIssueMaracasHistoricMetric">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dailyBugTrackerMigrationMaracasData" upperBound="-1" eType="//DailyBugTrackerMigrationMaracasData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bugTrackerMigrationMaracasData" upperBound="-1" eType="//BugTrackerMigrationMaracasData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DailyBugTrackerMigrationMaracasData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bugTrackerId">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bugsId" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfIssues">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BugTrackerMigrationMaracasData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bugTrackerId">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bugId">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changesAndMatchingPercentage" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
