/*
 * generated by Xtext 2.16.0
 */
package org.eclipse.scava.crossflow.language.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CrossflowProposalProvider extends AbstractCrossflowProposalProvider {
}
