from crossflow.runtime import Job


class Confirmation(Job):
    """NOTE: Auto-generated by Type2Class on 2019-12-19T16:51:07.797Z
    Do not edit this class manually
    """

    def __init__(self,
        repository_name: str = None,
        correlation: Job = None
    ):
        super().__init__()
        self._repository_name = repository_name
        if correlation is not None:
            self.correlationId = correlation.correlationId

    @property
    def repository_name(self) -> str:
        return self._repository_name

    @repository_name.setter
    def repository_name(self, repository_name: str):
        self._repository_name = repository_name

    def __str__(self):
        return f"Confirmation ( repository_name={self.repository_name}, jobId={self.jobId}, correlationId={self.correlationId}, destination={self.destination} )"
