from crossflow.runtime import Job


class Repository(Job):
    """NOTE: Auto-generated by Type2Class on 2019-12-19T16:51:07.797Z
    Do not edit this class manually
    """

    def __init__(self,
        path: str = None,
        url: str = None,
        commit: str = None,
        correlation: Job = None
    ):
        super().__init__()
        self._path = path
        self._url = url
        self._commit = commit
        if correlation is not None:
            self.correlationId = correlation.correlationId

    @property
    def path(self) -> str:
        return self._path

    @path.setter
    def path(self, path: str):
        self._path = path

    @property
    def url(self) -> str:
        return self._url

    @url.setter
    def url(self, url: str):
        self._url = url

    @property
    def commit(self) -> str:
        return self._commit

    @commit.setter
    def commit(self, commit: str):
        self._commit = commit

    def __str__(self):
        return f"Repository ( path={self.path}, url={self.url}, commit={self.commit}, jobId={self.jobId}, correlationId={self.correlationId}, destination={self.destination} )"
