{
    MimeMessage msg;
    String content;
    WorkItemImpl workItem = new WorkItemImpl();
    workItem.setParameter(  " a string " ,  " a string "  );
    workItem.setParameter(  " a string " ,  " a string "  );
    workItem.setParameter(  " a string " ,  " a string "  );
    workItem.setParameter(  " a string " ,  " a string "  );
    workItem.setParameter(  " a string " ,  " a string "  );

    WorkItemManager manager = new DefaultWorkItemManager(null);
    assertEquals( workItem.getParameter(  " a string "  ), content );
    assertEquals( workItem.getParameter(  " a string "  ), msg.getSubject() );
    assertEquals( workItem.getParameter(  " a string "  ), ((InternetAddress)msg.getFrom()[number]).getAddress() );
    assertEquals( workItem.getParameter(  " a string "  ), ((InternetAddress)msg.getReplyTo()[number]).getAddress() );
    assertEquals( workItem.getParameter(  " a string "  ), ((InternetAddress)msg.getRecipients( RecipientType.TO )[number]).getAddress() );
    // Do something with manager
}    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    assertEquals( workItem.getParameter(  "  " a string "  "  ), content );    assertEquals( workItem.getParameter(  "  " a string "  "  ), msg.getSubject() );    assertEquals( workItem.getParameter(  "  " a string "  "  ), ((InternetAddress)msg.getFrom()[number]).getAddress() );    assertEquals( workItem.getParameter(  "  " a string "  "  ), ((InternetAddress)msg.getReplyTo()[number]).getAddress() );    assertEquals( workItem.getParameter(  "  " a string "  "  ), ((InternetAddress)msg.getRecipients( RecipientType.TO )[number]).getAddress() );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    workItem.setParameter(  "  " a string "  " ,  "  " a string "  "  );    assertEquals( workItem.getParameter(  "  " a string "  "  ), content );    assertEquals( workItem.getParameter(  "  " a string "  "  ), msg.getSubject() );    assertEquals( workItem.getParameter(  "  " a string "  "  ), ((InternetAddress)msg.getFrom()[number]).getAddress() );    assertEquals( workItem.getParameter(  "  " a string "  "  ), ((InternetAddress)msg.getReplyTo()[number]).getAddress() );    assertEquals( workItem.getParameter(  "  " a string "  "  ), ((InternetAddress)msg.getRecipients( RecipientType.TO )[number]).getAddress() );}    workItem.setParameter(  "  "  " a string "  "  " ,  "  "  " a string "  "  "  );    workItem.setParameter(  "  "  " a string "  "  " ,  "  "  " a string "  "  "  );    workItem.setParameter(  "  "  " a string "  "  " ,  "  "  " a string "  "  "  );    workItem.setParameter(  "  "  " a string "  "  " ,  "  "  " a string "  "  "  );    workItem.setParameter(  "  "  " a string "  "  " ,  "  "  " a string "  "  "  );    assertEquals( workItem.getParameter(  "  "  " a string "  "  "  ), content );    assertEquals( workItem.getParameter(  "  "  " a string "  "  "  ), msg.getSubject() );    assertEquals( workItem.getParameter(  "  "  " a string "  "  "  ), ((InternetAddress)msg.getFrom()[number]).getAddress() );    assertEquals( workItem.getParameter(  "  "  " a string "  "  "  ), ((InternetAddress)msg.getReplyTo()[number]).getAddress() );    assertEquals( workItem.getParameter(  "  "  " a string "  "  "  ), ((InternetAddress)msg.getRecipients( RecipientType.TO )[number]).getAddress() );
