{
    ResourceSet resourceSet;
    DocumentRoot root;
    final String JBPM_PROCESS_EXTENSION;
    INakedElement behavior;
    HeaderType header;
    VariablesType variables;
    resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put(JBPM_PROCESS_EXTENSION, new ProcessResourceFactoryImpl());
    root.setProcess(ProcessFactory.eINSTANCE.createProcessType());
    ProcessType process = root.getProcess();
    process.getHeader().add(header);
    header.getVariables().add(variables);
    root.getProcess().getNodes().add(ProcessFactory.eINSTANCE.createNodesType());
    root.getProcess().getConnections().add(ProcessFactory.eINSTANCE.createConnectionsType());
    root.getProcess().setId(Jbpm5Util.generateProcessName(behavior));
    root.getProcess().setName(Jbpm5Util.generateProcessName(behavior));
    root.getProcess().setPackageName(behavior.getNameSpace().getMappingInfo().getQualifiedJavaName());
    root.getProcess().setVersion( " a string "  + workspace.getWorkspaceMappingInfo().getVersion().toVersionString());
    root.getProcess().setType( " a string " );
}    root.getProcess().setVersion( "  " a string "  "  + workspace.getWorkspaceMappingInfo().getVersion().toVersionString());    root.getProcess().setType( "  " a string "  " );    root.getProcess().setVersion( "  " a string "  "  + workspace.getWorkspaceMappingInfo().getVersion().toVersionString());    root.getProcess().setType( "  " a string "  " );}    root.getProcess().setVersion( "  "  " a string "  "  "  + workspace.getWorkspaceMappingInfo().getVersion().toVersionString());    root.getProcess().setType( "  "  " a string "  "  " );
