{
    Set<ParameterDefinition> parameterDefinitions;
    Work work = new WorkImpl();
    work.setName( " a string " );
    parameterDefinitions.add(new ParameterDefinitionImpl( " a string " , new StringDataType()));
    parameterDefinitions.add(new ParameterDefinitionImpl( " a string " , new StringDataType()));
    parameterDefinitions.add(new ParameterDefinitionImpl( " a string " , new StringDataType()));
    parameterDefinitions.add(new ParameterDefinitionImpl( " a string " , new StringDataType()));
    parameterDefinitions.add(new ParameterDefinitionImpl( " a string " , new StringDataType()));
    parameterDefinitions.add(new ParameterDefinitionImpl( " a string " , new StringDataType()));
    work.setParameterDefinitions(parameterDefinitions);
}    work.setName( "  " a string "  " );    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    work.setName( "  " a string "  " );    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  " a string "  " , new StringDataType()));}    work.setName( "  "  " a string "  "  " );    parameterDefinitions.add(new ParameterDefinitionImpl( "  "  " a string "  "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  "  " a string "  "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  "  " a string "  "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  "  " a string "  "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  "  " a string "  "  " , new StringDataType()));    parameterDefinitions.add(new ParameterDefinitionImpl( "  "  " a string "  "  " , new StringDataType()));
