{
    StatefulKnowledgeSession ksession;
    ksession.getWorkItemManager().registerWorkItemHandler( " a string " , new SystemOutWorkItemHandler());
    ksession.getWorkItemManager().registerWorkItemHandler( " a string " , new DoNothingWorkItemHandler());
    ProcessInstance processInstance = ksession.startProcess( " a string " );
    assertTrue(processInstance.getState() == ProcessInstance.STATE_ACTIVE);
    ksession.getWorkItemManager().registerWorkItemHandler( " a string " , new SystemOutWorkItemHandler());
    ksession.getWorkItemManager().registerWorkItemHandler( " a string " , new DoNothingWorkItemHandler());
    ksession.signalEvent( " a string " ,  " a string " , processInstance.getId());
    assertTrue(processInstance.getState() == ProcessInstance.STATE_ACTIVE);
    ksession.getWorkItemManager().registerWorkItemHandler( " a string " , new SystemOutWorkItemHandler());
    ksession.getWorkItemManager().registerWorkItemHandler( " a string " , new DoNothingWorkItemHandler());
    ksession.signalEvent( " a string " ,  " a string " , processInstance.getId());
}    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new DoNothingWorkItemHandler());    ProcessInstance processInstance = ksession.startProcess( "  " a string "  " );    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new DoNothingWorkItemHandler());    ksession.signalEvent( "  " a string "  " ,  "  " a string "  " , processInstance.getId());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new DoNothingWorkItemHandler());    ksession.signalEvent( "  " a string "  " ,  "  " a string "  " , processInstance.getId());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new DoNothingWorkItemHandler());    ProcessInstance processInstance = ksession.startProcess( "  " a string "  " );    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new DoNothingWorkItemHandler());    ksession.signalEvent( "  " a string "  " ,  "  " a string "  " , processInstance.getId());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  " a string "  " , new DoNothingWorkItemHandler());    ksession.signalEvent( "  " a string "  " ,  "  " a string "  " , processInstance.getId());}    ksession.getWorkItemManager().registerWorkItemHandler( "  "  " a string "  "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  "  " a string "  "  " , new DoNothingWorkItemHandler());    ProcessInstance processInstance = ksession.startProcess( "  "  " a string "  "  " );    ksession.getWorkItemManager().registerWorkItemHandler( "  "  " a string "  "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  "  " a string "  "  " , new DoNothingWorkItemHandler());    ksession.signalEvent( "  "  " a string "  "  " ,  "  "  " a string "  "  " , processInstance.getId());    ksession.getWorkItemManager().registerWorkItemHandler( "  "  " a string "  "  " , new SystemOutWorkItemHandler());    ksession.getWorkItemManager().registerWorkItemHandler( "  "  " a string "  "  " , new DoNothingWorkItemHandler());    ksession.signalEvent( "  "  " a string "  "  " ,  "  "  " a string "  "  " , processInstance.getId());
